#!/bin/bash
cmd=$1
file=$2
echo -e "Command is - $cmd\nFile name is - $file\nCommit message is - Added $file"
echo '#!/bin/bash' > $file
echo "$cmd" >> $file
chmod u+x $file
git add .
git commit -m "Added $file"
git push
